package sync;


/**
* sync/Sync.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sync.idl
* Saturday, 23 October 2010 6:51:02 PM EST
*/


// the methods which will be used by the corba service).
public interface Sync extends SyncOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sync
