package sync;


/**
* sync/SyncPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sync.idl
* Saturday, 23 October 2010 6:51:02 PM EST
*/


// the methods which will be used by the corba service).
public abstract class SyncPOA extends org.omg.PortableServer.Servant
 implements sync.SyncOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCharacter", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // The getCharacter() method declaration for the random character service.
       case 0:  // sync/Sync/getCharacter
       {
         char $result = (char)0;
         $result = this.getCharacter ();
         out = $rh.createReply();
         out.write_char ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sync/Sync:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Sync _this() 
  {
    return SyncHelper.narrow(
    super._this_object());
  }

  public Sync _this(org.omg.CORBA.ORB orb) 
  {
    return SyncHelper.narrow(
    super._this_object(orb));
  }


} // class SyncPOA
