package sync;

/**
* sync/SyncHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sync.idl
* Saturday, 23 October 2010 6:50:55 PM EST
*/


// the methods which will be used by the corba service).
public final class SyncHolder implements org.omg.CORBA.portable.Streamable
{
  public sync.Sync value = null;

  public SyncHolder ()
  {
  }

  public SyncHolder (sync.Sync initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sync.SyncHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sync.SyncHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sync.SyncHelper.type ();
  }

}
